<?php

return array(
    'aryDoctorStar' => array('一星', '二星', '三星', '四星', '五星'),
    'aryOrderPayStatus' => array('未付款', '已付款', '待退款', '已退款'),
    'aryOrderPayType' => array('未选择', '微信', '支付宝'),
    'base_host' => 'http://api.judeng.net',
    'ose_host' => 'http://api.judeng.net',
    'aryOrderType' => array('问诊', '复诊', '诊后咨询', '处方订单', '自建产品', '历史开方'),
    'aryOrderStatus' => array(
        '-1' => '已取消',
        '0' => '待付款',
        '1' => '待发货',
        '2' => '待收货',
        '3' => '待评价',
        '4' => '已完成',
        '5' => '待退货',
        '6' => '已退货',
        '7' => '已过期',
        '8' => '待审核',
    ),
    'aryDisplay' => array('否', '是'),
    'arySex' => array('男', '女'),
    'aryServiceEvaluation' => array('很满意', '满意', '还可以'),
    'aryMemberType' => array('公众号患者', '手机号患者'),
    'aryMemberType1' => array('已关注公众号', '未关注公众号'),
    'aryCertified' => array('未认证', '审核中', '认证通过', '认证失败'),
    'aryCream' => array(
        '膏方内包装',
        '膏方外包装',
    ),
    'aryHisState' => array(
        '三九颗粒剂' => '0,1,2',
        '不盘存橱柜' => '0,1,4',
        '中成药柜' => '5',
        '中药' => '0,1,4',
        '农本方' => '0,1,4',
        '外用药柜' => '0,1,4',
        '常用饮片' => '0,1,4',
        '无用药柜' => '0,1,4',
        '精致饮片' => '3',
        '西药药柜' => '5',
        '贵细' => '0,1,4',
        '辅料' => '0,1,4',
        '针剂' => '0,1,4',
        '颗粒' => '0,1,2',
    ),
);